/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao;

import br.com.controle.Conta;
import javax.swing.JOptionPane;

/**
 *
 * @author valdemir.moreira
 */
public class Banco extends javax.swing.JFrame {

    private final Conta conta = new Conta();

    /**
     * Creates new form Banco
     */
    public Banco() {
        initComponents();
        this.atualizarSaldoNaTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLvalor = new javax.swing.JLabel();
        jBsair = new javax.swing.JButton();
        jBsaldo = new javax.swing.JButton();
        jBsaque = new javax.swing.JButton();
        jBdeposito = new javax.swing.JButton();
        jTvalor = new javax.swing.JTextField();
        jLsaltoatual = new javax.swing.JLabel();
        jLmensagem = new javax.swing.JLabel();
        jBcorrente = new javax.swing.JButton();
        jBpoupanca = new javax.swing.JButton();
        jLconta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLvalor.setText("valor R$:");

        jBsair.setText("sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jBsaldo.setText("Saldo");
        jBsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsaldoActionPerformed(evt);
            }
        });

        jBsaque.setText("Saque");
        jBsaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsaqueActionPerformed(evt);
            }
        });

        jBdeposito.setText("Deposito");
        jBdeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdepositoActionPerformed(evt);
            }
        });

        jTvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvalorActionPerformed(evt);
            }
        });

        jLmensagem.setForeground(new java.awt.Color(255, 0, 0));
        jLmensagem.setText("                      Transação");

        jBcorrente.setText("corrente");
        jBcorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcorrenteActionPerformed(evt);
            }
        });

        jBpoupanca.setText("poupança");
        jBpoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpoupancaActionPerformed(evt);
            }
        });

        jLconta.setForeground(new java.awt.Color(255, 51, 51));
        jLconta.setText("                    Tipo de conta ");

        jLabel1.setText("Opção:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBsaldo)
                            .addComponent(jLvalor)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLsaltoatual, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBcorrente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBpoupanca)))
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBdeposito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBsaque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBsair))
                            .addComponent(jTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLmensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLconta, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcorrente)
                    .addComponent(jBpoupanca)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLconta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLsaltoatual, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsaldo))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTvalor, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBdeposito)
                    .addComponent(jBsaque)
                    .addComponent(jBsair))
                .addGap(39, 39, 39)
                .addComponent(jLmensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBsairActionPerformed

    private void jTvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvalorActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTvalorActionPerformed

    private void jBdepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdepositoActionPerformed

        try {

            final Double valor = Double.parseDouble(jTvalor.getText());

            this.conta.depositar(valor);

            this.atualizarSaldoNaTela();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Valor informado não é numérico!");
        } catch (NullPointerException e) {

            JOptionPane.showMessageDialog(null, "Informe um valor para realizar esta operação!");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Ops! " + e.getMessage());
        }


    }//GEN-LAST:event_jBdepositoActionPerformed

    private void jBsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsaldoActionPerformed
        // TODO add your handling code here:
        jLsaltoatual.setText(String.valueOf(this.conta.saldo()));
        //jLsaltoatual.setText(Double.valueOf(saldo));
    }//GEN-LAST:event_jBsaldoActionPerformed

    private void jBcorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcorrenteActionPerformed
        // TODO add your handling code here:
        jLconta.setText("Conta Corrente");
    }//GEN-LAST:event_jBcorrenteActionPerformed

    private void jBpoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpoupancaActionPerformed
        // TODO add your handling code here:
        jLconta.setText("Conta poupança");
    }//GEN-LAST:event_jBpoupancaActionPerformed

    private void jBsaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsaqueActionPerformed
        try {

            final Double valor = Double.parseDouble(jTvalor.getText());

            this.conta.sacar(valor);

            this.atualizarSaldoNaTela();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Valor informado não é numérico!");
        } catch (NullPointerException e) {

            JOptionPane.showMessageDialog(null, "Informe um valor para realizar esta operação!");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Ops! " + e.getMessage());
        }
    }//GEN-LAST:event_jBsaqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Banco().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcorrente;
    private javax.swing.JButton jBdeposito;
    private javax.swing.JButton jBpoupanca;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsaldo;
    private javax.swing.JButton jBsaque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLconta;
    private javax.swing.JLabel jLmensagem;
    private javax.swing.JLabel jLsaltoatual;
    private javax.swing.JLabel jLvalor;
    private javax.swing.JTextField jTvalor;
    // End of variables declaration//GEN-END:variables

    private void atualizarSaldoNaTela() {
        jLsaltoatual.setText(String.valueOf(conta.saldo()));
    }
}
